// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHseExpuOJSyrK9LOR10-9kTZN0yaIf_Y',
    appId: '1:467833457075:web:d6c137fae1ac009b9023c6',
    messagingSenderId: '467833457075',
    projectId: 'oracle-96544',
    authDomain: 'oracle-96544.firebaseapp.com',
    storageBucket: 'oracle-96544.firebasestorage.app',
    measurementId: 'G-XJC3VCT9Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_3fQLIXIg7zHMjE-FHQ8oEX2nqDPcH7s',
    appId: '1:467833457075:android:5f104c11957aedef9023c6',
    messagingSenderId: '467833457075',
    projectId: 'oracle-96544',
    storageBucket: 'oracle-96544.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApAC-EK_7XHpXIPr8cZKG6mQQalzZOGb4',
    appId: '1:467833457075:ios:b289fc76e55898559023c6',
    messagingSenderId: '467833457075',
    projectId: 'oracle-96544',
    storageBucket: 'oracle-96544.firebasestorage.app',
    iosBundleId: 'com.example.fitnessAppSaas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApAC-EK_7XHpXIPr8cZKG6mQQalzZOGb4',
    appId: '1:467833457075:ios:b289fc76e55898559023c6',
    messagingSenderId: '467833457075',
    projectId: 'oracle-96544',
    storageBucket: 'oracle-96544.firebasestorage.app',
    iosBundleId: 'com.example.fitnessAppSaas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHseExpuOJSyrK9LOR10-9kTZN0yaIf_Y',
    appId: '1:467833457075:web:7e8fe5f5e84e220d9023c6',
    messagingSenderId: '467833457075',
    projectId: 'oracle-96544',
    authDomain: 'oracle-96544.firebaseapp.com',
    storageBucket: 'oracle-96544.firebasestorage.app',
    measurementId: 'G-KGW9YC7DPQ',
  );
}
